-- MySQL Script generated by MySQL Workbench
-- Sat Apr 14 15:32:56 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Place` (
  `idPlace` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `text_address` VARCHAR(100) NULL COMMENT '',
  `description` VARCHAR(200) NULL COMMENT '',
  `lat` DECIMAL(3,7) NULL COMMENT '',
  `long` DECIMAL(3,7) NULL COMMENT '',
  PRIMARY KEY (`idPlace`)  COMMENT '',
  UNIQUE INDEX `idPlace_UNIQUE` (`idPlace` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nom` VARCHAR(45) NULL COMMENT '',
  `prenom` VARCHAR(45) NULL COMMENT '',
  `login` VARCHAR(45) NULL COMMENT '',
  `eco_result` DECIMAL(10,2) NULL COMMENT '',
  `mail` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idUser`)  COMMENT '',
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Car` (
  `idCar` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `model` VARCHAR(45) NULL COMMENT '',
  `color` VARCHAR(20) NULL COMMENT '',
  `nb_seats` INT NULL COMMENT '',
  `owner` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idCar`)  COMMENT '',
  UNIQUE INDEX `idCar_UNIQUE` (`idCar` ASC)  COMMENT '',
  INDEX `fk_Car_User_idx` (`owner` ASC)  COMMENT '',
  CONSTRAINT `fk_Car_User`
    FOREIGN KEY (`owner`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ride`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ride` (
  `idRide` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `description` VARCHAR(200) NULL COMMENT '',
  `nb_free_seats` INT NULL COMMENT '',
  `value_luggage` INT NULL COMMENT '',
  `car` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idRide`)  COMMENT '',
  UNIQUE INDEX `idRide_UNIQUE` (`idRide` ASC)  COMMENT '',
  INDEX `fk_Ride_Car1_idx` (`car` ASC)  COMMENT '',
  CONSTRAINT `fk_Ride_Car1`
    FOREIGN KEY (`car`)
    REFERENCES `mydb`.`Car` (`idCar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Step`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Step` (
  `idStep` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `distance` VARCHAR(45) NULL COMMENT '',
  `departure_time` DATETIME NULL COMMENT '',
  `eco_result` DECIMAL(10,2) NULL COMMENT '',
  `duration` TIME(0) NULL COMMENT '',
  `description` VARCHAR(200) NULL COMMENT '',
  `departure` INT NOT NULL COMMENT '',
  `arrival` INT NOT NULL COMMENT '',
  `ride` INT NOT NULL COMMENT '',
  `price` DECIMAL(3,2) NULL DEFAULT 0 COMMENT '',
  PRIMARY KEY (`idStep`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`idStep` ASC)  COMMENT '',
  INDEX `fk_Step_Place1_idx` (`departure` ASC)  COMMENT '',
  INDEX `fk_Step_Place2_idx` (`arrival` ASC)  COMMENT '',
  INDEX `fk_Step_Ride1_idx` (`ride` ASC)  COMMENT '',
  CONSTRAINT `fk_Step_Place1`
    FOREIGN KEY (`departure`)
    REFERENCES `mydb`.`Place` (`idPlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Step_Place2`
    FOREIGN KEY (`arrival`)
    REFERENCES `mydb`.`Place` (`idPlace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Step_Ride1`
    FOREIGN KEY (`ride`)
    REFERENCES `mydb`.`Ride` (`idRide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`is_passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`is_passenger` (
  `ride` INT NOT NULL COMMENT '',
  `user` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ride`, `user`)  COMMENT '',
  INDEX `fk_Ride_has_User_User1_idx` (`user` ASC)  COMMENT '',
  INDEX `fk_Ride_has_User_Ride1_idx` (`ride` ASC)  COMMENT '',
  CONSTRAINT `fk_Ride_has_User_Ride1`
    FOREIGN KEY (`ride`)
    REFERENCES `mydb`.`Ride` (`idRide`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ride_has_User_User1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
